name: recetas360
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  firebase_dynamic_links: ^6.1.5 # O la última versión disponible
  firebase_analytics: ^11.4.5 # Añade esta línea (o la última versión)
  cloud_functions: ^5.5.0
  # State Management & Utilities
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  http: ^1.3.0
  

  # --- Added for Redesign ---
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  # --- End of added packages ---

  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  flutter_rating_bar: ^4.0.1
  share_plus: ^11.0.0
  # Replace audioplayers with just_audio
  just_audio: ^0.9.36
  audio_session: ^0.1.18 # Add or ensure this line is present
  # Gemini API
  google_generative_ai: ^0.4.0 # O la última versión estable disponible
  flutter_dotenv: ^5.1.0 # Asegúrate de tener esta o una versión compatible


# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # <--- AÑADIDO

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/sounds/notification.mp3
    - assets/icon/ # <--- ASEGÚRATE DE QUE ESTA CARPETA (O DONDE ESTÉ TU ICONO) ESTÉ LISTADA SI ES NECESARIO PARA OTROS PROPÓSITOS
  # --- SECCIÓN DE FUENTES AÑADIDA/MODIFICADA ---
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Configuración para flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon" # Nombre del icono para Android
  ios: true
  image_path: "assets/icon/logo.png" # Ruta a tu imagen de icono principal
  min_sdk_android: 21 # Requerido para iconos adaptativos
  adaptive_icon_foreground: "assets/icon/logo.png" # Si tu icono principal ya tiene el diseño final, puedes reusarlo.           
  remove_alpha_ios: true
